create table if not exists public.media (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('photo','video')),
  path text not null unique,
  public_url text not null,
  created_at timestamptz not null default now()
);

alter table public.media enable row level security;

drop policy if exists "Anyone can view media" on public.media;
create policy "Anyone can view media"
on public.media for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can add media" on public.media;
create policy "Anyone can add media"
on public.media for insert
to anon, authenticated
with check (true);

-- Storage upload policy
drop policy if exists "Anyone can upload OneClass media" on storage.objects;
create policy "Anyone can upload OneClass media"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'oneclass-media');
